CREATE TABLE videos (
    id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    "user" VARCHAR(100) NOT NULL,
    CONSTRAINT VIDEOS_PK_CONSTRAINT PRIMARY KEY (id)
);

CREATE TABLE hashtags (
    tag VARCHAR(100) NOT NULL,
    CONSTRAINT HASHTAGS_PK_CONSTRAINT PRIMARY KEY (tag)
);

CREATE TABLE video_hashtags (
    video INT REFERENCES videos(id) ON DELETE SET NULL,
    hashtag VARCHAR(100) REFERENCES hashtags(tag) ON DELETE SET NULL
);

CREATE TABLE likes (
    id INT NOT NULL,
    "user" VARCHAR(100) NOT NULL,
    video INT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
    CONSTRAINT LIKES_PK_CONSTRAINT PRIMARY KEY (id)
);

CREATE TABLE dislikes (
   id INT NOT NULL,
   "user" VARCHAR(100) NOT NULL,
   video INT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
   CONSTRAINT DISLIKES_PK_CONSTRAINT PRIMARY KEY (id)
);

CREATE TABLE views (
   id INT NOT NULL,
   "user" VARCHAR(100) NOT NULL,
   video INT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
   CONSTRAINT VIEWS_PK_CONSTRAINT PRIMARY KEY (id)
)