version: '3'

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    deploy:
      replicas: 1
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    deploy:
      replicas: 1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: INTERNAL://:9093,OUTSIDE://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      ALLOW_PLAINTEXT_LISTENER: "yes"

  vm-db:
    image: postgres:latest
    ports:
      - '5051:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'VM_DB'
    restart: unless-stopped

  thm-db:
    image: postgres:latest
    ports:
      - '5052:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'THM_DB'
    restart: unless-stopped

  sm-db:
    image: postgres:latest
    ports:
      - '5053:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'SM_DB'
    restart: unless-stopped

  vm:
    image: vm:latest
    ports:
      - "8081:8081"
    depends_on:
      - vm-db
      - kafka

  thm:
    image: thm:latest
    ports:
      - "8082:8082"
    depends_on:
      - thm-db
      - kafka

  sm:
    image: sm:latest
    ports:
      - "8083:8083"
    depends_on:
      - sm-db
      - kafka