version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  vm-db:
    image: postgres:latest
    ports:
      - '5051:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'VM_DB'
    restart: unless-stopped

  thm-db:
    image: postgres:latest
    ports:
      - '5052:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'THM_DB'
    restart: unless-stopped

  sm-db:
    image: postgres:latest
    ports:
      - '5053:5432'
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'SM_DB'
    restart: unless-stopped

  vm:
    image: vm:latest
    ports:
      - "8081:8081"
    depends_on:
      - vm-db
      - kafka

  thm:
    image: thm:latest
    ports:
      - "8082:8082"
    depends_on:
      - thm-db
      - kafka

  sm:
    image: sm:latest
    ports:
      - "8083:8083"
    depends_on:
      - sm-db
      - kafka