version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  vidcraze-db:
    image: postgres:latest
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: VM_DB,THM_DB,SM_DB
      POSTGRES_PASSWORD: 'password'
    restart: unless-stopped

  vm:
    image: vm:latest
    ports:
      - "8081:8081"
    environment:
      JDBC_HOST: vidcraze-db
      JDBC_PORT: 5432
      JDBC_SCHEMA: vm_db
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      ZIPKIN_URL: 'http://zipkin:9411'
    depends_on:
      - vidcraze-db
      - kafka
    restart: unless-stopped

  thm:
    image: thm:latest
    ports:
      - "8082:8082"
    environment:
      JDBC_HOST: vidcraze-db
      JDBC_PORT: 5432
      JDBC_SCHEMA: thm_db
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      ZIPKIN_URL: 'http://zipkin:9411'
    depends_on:
      - vidcraze-db
      - kafka
    restart: unless-stopped

  sm:
    image: sm:latest
    ports:
      - "8083:8083"
    environment:
      JDBC_HOST: vidcraze-db
      JDBC_PORT: 5432
      JDBC_SCHEMA: sm_db
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      ZIPKIN_URL: 'http://zipkin:9411'
    depends_on:
      - vidcraze-db
      - kafka
    restart: unless-stopped