version: '3'

services:

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      JMX_PORT: 9997
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=kafka -Dcom.sun.management.jmxremote.rmi.port=9997
#    volumes:
#      - ./.kafkadata:/bitnami

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '9090:8080'
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: 'true'

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  vidcraze-db:
    image: postgres:latest
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_MULTIPLE_DATABASES: VM_DB,THM_DB,SM_DB
      POSTGRES_PASSWORD: 'password'
    restart: unless-stopped

  vm:
    image: vm:latest
    ports:
      - "8081:8081"
    environment:
      JDBC_HOST: vidcraze-db
      JDBC_PORT: 5432
      JDBC_SCHEMA: vm_db
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      ZIPKIN_URL: 'http://zipkin:9411'
    depends_on:
      - vidcraze-db
      - kafka
    restart: unless-stopped

  thm:
    image: thm:latest
    ports:
      - "8082:8082"
    environment:
      JDBC_HOST: vidcraze-db
      JDBC_PORT: 5432
      JDBC_SCHEMA: thm_db
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      ZIPKIN_URL: 'http://zipkin:9411'
    depends_on:
      - vidcraze-db
      - kafka
    restart: unless-stopped

  sm:
    image: sm:latest
    ports:
      - "8083:8083"
    environment:
      JDBC_HOST: vidcraze-db
      JDBC_PORT: 5432
      JDBC_SCHEMA: sm_db
      JDBC_USER: postgres
      JDBC_PASSWORD: password
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      ZIPKIN_URL: 'http://zipkin:9411'
    depends_on:
      - vidcraze-db
      - kafka
    restart: unless-stopped