micronaut:
  server:
    port: 8082
  application:
    name: thm

datasources:
  default:
    db-type: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
    jdbc-url: 'jdbc:postgresql://localhost:5052/THM_DB'
    username: 'postgres'
    password: 'password'


flyway:
  datasources:
    default:
      enabled: false

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: 'update'

kafka:
  bootstrap:
    servers: localhost:9092
  streams:
    default:
      processing.guarantee: "exactly_once"
      auto.offset.reset: "earliest"



