CREATE DATABASE vm_db;
CREATE DATABASE thm_db;
CREATE DATABASE sm_db;

GRANT ALL PRIVILEGES ON DATABASE vm_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE thm_db TO postgres;
GRANT ALL PRIVILEGES ON DATABASE sm_db TO postgres;