micronaut:
  server:
    port: 8083
  application:
    name: sm

datasources:
  default:
    db-type: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
    jdbc-url: 'jdbc:postgresql://${JDBC_HOST:localhost}:${JDBC_PORT:5432}/${JDBC_SCHEMA:sm_db}'
    username: '${JDBC_USER:postgres}'
    password: '${JDBC_PASSWORD:password}'


flyway:
  datasources:
    default:
      enabled: false

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: 'update'

kafka:
  bootstrap:
    servers: '${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}'

tracing:
  zipkin:
    enabled: true
    http:
      url: "${ZIPKIN_URL:'http://localhost:9411'}"
    sampler:
      probability: 1