micronaut:
  server:
    port: 8083
  application:
    name: sm

datasources:
  default:
    db-type: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
    jdbc-url: 'jdbc:postgresql://${JDBC_HOST:localhost}:${JDBC_PORT:5053}/SM_DB'
    username: 'postgres'
    password: 'password'


flyway:
  datasources:
    default:
      enabled: false

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: 'update'

kafka:
  bootstrap:
    servers: '${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}'

otel:
  traces:
    exporter: zipkin